#!/usr/bin/env python3
"""
Downloads public review snippets for ONE Google Maps place via the
Legacy Places Details API and writes ../data/google-reviews.json.

Prerequisites:
  - Google Cloud project with \"Places API\" enabled (legacy API name is fine).
  - API key restricted to Places API / server IP if you run this from CI.

Environment:
  GOOGLE_MAPS_API_KEY   required
  GOOGLE_PLACE_ID       required (ChIJ… or newer place id string)

Finding Place ID: open Maps > your listing > Share > Embed a map — the URL often
contains \"!1s0x…\" fragments; simpler: use Google's Place ID tools linked from
https://developers.google.com/maps/documentation/places/web-service/place-id

Note: Details JSON returns at most five review objects per Google; user_ratings_total
is usually higher.
"""

from __future__ import annotations

import json
import os
import sys
from urllib.error import HTTPError, URLError
from urllib.parse import urlencode
from urllib.request import urlopen


def fail(msg: str, code: int = 1) -> None:
    print(msg, file=sys.stderr)
    raise SystemExit(code)


def main() -> None:
    key = os.environ.get("GOOGLE_MAPS_API_KEY", "").strip()
    place_id = os.environ.get("GOOGLE_PLACE_ID", "").strip()
    out_path = os.path.join(os.path.dirname(__file__), "..", "data", "google-reviews.json")

    if not key or not place_id:
        fail(
            "Set GOOGLE_MAPS_API_KEY and GOOGLE_PLACE_ID.\nExample (PowerShell):\n"
            '  $env:GOOGLE_MAPS_API_KEY="YOUR_KEY"\n'
            '  $env:GOOGLE_PLACE_ID="ChIJ…"\n'
            "  python scripts/fetch_google_reviews.py"
        )

    fields = ",".join(
        [
            "name",
            "rating",
            "user_ratings_total",
            "reviews",
            "url",
        ]
    )
    qs = urlencode(
        {
            "place_id": place_id,
            "fields": fields,
            "reviews_sort": "newest",
            "reviews_no_translations": "true",
            "key": key,
        }
    )
    url = "https://maps.googleapis.com/maps/api/place/details/json?" + qs

    try:
        with urlopen(url, timeout=45) as resp:
            payload = json.load(resp)
    except HTTPError as e:
        fail("HTTP error: {} {}".format(e.code, e.reason))
    except URLError as e:
        fail("Network error: {}".format(e.reason))
    except json.JSONDecodeError as e:
        fail("Bad JSON from Google: {}".format(e))

    status = payload.get("status")
    if status != "OK":
        fail("Places API returned status={}: {}".format(status, payload.get("error_message")))

    result = payload.get("result") or {}
    google_reviews = result.get("reviews") or []

    reviews_out = []
    for r in google_reviews:
        reviews_out.append(
            {
                "authorName": r.get("author_name"),
                "rating": r.get("rating"),
                "text": (r.get("text") or "").strip(),
                "relativeTimeDescription": r.get("relative_time_description") or "",
                "subtitle": "",
                "reviewTimeUtcSeconds": r.get("time"),
                "profilePhotoUrl": r.get("profile_photo_url") or "",
            }
        )

    data = {
        "placeName": result.get("name") or "United Flooring America",
        "placeId": place_id,
        "googleMapsUrl": result.get("url") or "",
        "rating": result.get("rating"),
        "userRatingsTotal": result.get("user_ratings_total"),
        "reviews": reviews_out,
        "meta": {
            "source": "google_api",
            "syncedAt": "",  # optional: fill with ISO8601 externally if needed
            "hint": "Generated by scripts/fetch_google_reviews.py",
        },
    }

    os.makedirs(os.path.dirname(out_path), exist_ok=True)
    with open(out_path, "w", encoding="utf-8", newline="\n") as fh:
        json.dump(data, fh, ensure_ascii=False, indent=2)

    print(
        "Wrote {} reviews to {}".format(len(reviews_out), os.path.abspath(out_path))
    )


if __name__ == "__main__":
    main()
